# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.cBMdWD installed on Wed Mar 28 15:45:46 2012)
# (Cronie version 4.2)
#this executes the script every 5 minutes:
*/5 * * * * php ~cse156/public_html/grade/processKiller/Process.php
